config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  resources :categories
  resources :user_clips
  resources :clips, only: [:index, :show]
  resources :articles
  devise_for :users
  get 'home/index'
  get 'inquiries/thanks' => 'inquiries#thanks'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user_clip.rb
class UserClip < ApplicationRecord
  belongs_to :user
  belongs_to :clip
end

app/controllers/user_clips_controller.rb
class UserClipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_clip, only: [:show, :edit, :update, :destroy]

  # GET /user_clips
  # GET /user_clips.json
  def index
    #@user_clips = UserClip.all
    @clips = current_user.user_clips.order(created_at: :desc)
  end

  # GET /user_clips/1
  # GET /user_clips/1.json
  def show
    @clip = @user_clip.clip
  end

  # GET /user_clips/new
  def new
    @user_clip = UserClip.new
  end

  # GET /user_clips/1/edit
  def edit
  end

  # POST /user_clips
  # POST /user_clips.json
  def create
    @clip = Clip.find_or_initialize_by(url: params[:url])
    @user_clip = current_user.user_clips.build(clip: @clip)
    #@clip = Clip.find_by(url: params[:url])  
    #unless @clip
      #@clip = Clip.new(url: params[:url])
    #end
    respond_to do |format|
      if @clip.save && @user_clip.save
        format.html { redirect_to  user_clips_url, notice: 'User clip was successfully created.' }
        format.json { render :show, status: :created, location: @user_clip }
      else
        format.html { render :new }
        format.json { render json: @user_clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_clips/1
  # PATCH/PUT /user_clips/1.json
  def update
    respond_to do |format|
      if @user_clip.update(user_clip_params)
        format.html { redirect_to @user_clip, notice: 'User clip was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_clip }
      else
        format.html { render :edit }
        format.json { render json: @user_clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_clips/1
  # DELETE /user_clips/1.json
  def destroy
    @user_clip.destroy
    respond_to do |format|
      format.html { redirect_to user_clips_url, notice: 'User clip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_clip
      @user_clip = UserClip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_clip_params
      params.require(:user_clip).permit(:user_id, :clip_id)
    end
end

app/helpers/user_clips_helper.rb
module UserClipsHelper
end

app/views/user_clips/_form.html.erb
<%= form_with(model: user_clip, local: true) do |form| %>
  <% if clip = user_clip.clip %>
    <% if clip.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(clip.errors.count, "error") %> prohibited this user_clip from being saved:</h2>
  
        <ul>
        <% clip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>  

  <div class="field">
    <%= label_tag :url %>
    <%= text_field_tag :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_clips/edit.html.erb
<h1>Editing User Clip</h1>

<%= render 'form', user_clip: @user_clip %>

<%= link_to 'Show', @user_clip %> |
<%= link_to 'Back', user_clips_path %>

app/views/user_clips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Clips</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>User</th>
      <th>Clip</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @clips.each do |user_clip| %>
    <% clip = user_clip.clip %>
      <tr>
        <td><%= clip.url %></td>
        <td><%= clip.title %></td>
        <td><%= clip.description %></td>
        <td><%= image_tag clip.image, width: 200 if clip.image %></td>
        <td><%= link_to 'Show', clip_path(clip) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Clip', new_user_clip_path %>

app/views/user_clips/new.html.erb
<h1>New User Clip</h1>

<%= render 'form', user_clip: @user_clip %>

<%= link_to 'Back', user_clips_path %>

app/views/user_clips/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @clip.title %></h1>
<p><%= @clip.description %></p>
<p>
  <%= image_tag @clip.image, width: 500 if @clip.imge %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_clip.user %>
</p>

<p>
  <strong>Clip:</strong>
  <%= @user_clip.clip %>
</p>

<%= link_to 'Edit', edit_user_clip_path(@user_clip) %> |
<%= link_to 'Back', user_clips_path %>